sudo: required
language: node_js

branches:
  only:
    - develop

services:
  - docker

script:
  - docker build -t apinf/apinf:"$TRAVIS_BRANCH" .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push apinf/apinf:"$TRAVIS_BRANCH"
