dist: xenial

language: node_js
node_js:
  - '8'
  
language: python
python:
  - "2.7"  

addons:  
  chrome: stable

branches:
  only:
    - develop

before_cache:
  - rm -f $HOME/.meteor/log/*.log

services:
  - docker
  - xvfb

before_install:
  - ls -la
  - sudo apt-get update
  - sudo apt-get install g++ build-essential xvfb  
  
# Install meteor locally on CI
  - if [ ! -e "$HOME/.meteor/meteor" ]; then cat .travis_install_meteor | sed s/--progress-bar/-sL/g | /bin/sh; fi

before_script:
#Previously used yarn, but now after migrating to meteor 1.8, yarn fails to create some binaries.
  - meteor npm install
#Need to install chromedriver by hand
  - wget http://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
  - npm run lint
  - npm view chimp version
  - npm view chromedriver version
  
install:
  - export PATH="$HOME/.meteor:$PATH"

script:
  # Run meteor and chimp from node.js
  - travis_retry npm run test
  # Build docker image
  - ./.scripts/docker_build.sh

env:
  global:
  - DISPLAY=:99.0
  - TEST_MODE: "true" 
