sudo: false
language: node_js
node_js:
  - "node"

branches:
  only:
    - develop

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

services:
  - docker

before_script:
  - yarn run lint

script:
  - ./.scripts/docker_build.sh
